# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # Gatilho de build para a branch 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Passo 1: Preparar o ambiente
  - script: echo "Preparando o ambiente..."
    displayName: 'Preparar Ambiente'

  # Passo 2: Executar algum processo
  - script: echo "Executando o processo principal..."
    displayName: 'Executar Processo'

  # Passo 3: Realizar uma tarefa de teste
  - script: echo "Executando testes..."
    displayName: 'Executar Testes'

  # Passo 4: Publicar os resultados
  - script: echo "Publicando resultados..."
    displayName: 'Publicar Resultados'


